openapi: 3.2.0
info:
  version: 1.0.0
  title: Wikimedia REST Citation API
  description: This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats.
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Services team
    url: http://mediawiki.org/wiki/Wikimedia_REST_API
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
- url: /api/rest_v1
tags:
- name: Citation
  description: generation of citation data
paths:
  /data/citation/{format}/{query}:
    get:
      tags:
      - Citation
      summary: Get citation data given an article identifier
      description: 'Generates citation data given a URL, DOI, PMID, or PMCID.


        Automated requests can be made at a rate of 1 request per second (rps).


        See more at Citoid service documentation


        The citation data can be requested in one of the following formats:

        - `mediawiki`: format designed for MediaWiki to be used with `templateData`.

        Uses Zotero field names.

        - `mediawiki-basefields`: `mediawiki` format with Zotero `basefield` field names.

        - `zotero`: format used by Zotero.

        - `bibtex`: format used in conjunction with LaTeX documents.

        See bibtex.org.

        - `wikibase`: format designed for Wikibase.


        Stability: unstable'
      parameters:
      - name: format
        in: path
        description: The format to use for the resulting citation data
        schema:
          type: string
          enum:
          - mediawiki
          - mediawiki-basefields
          - zotero
          - bibtex
          - wikibase
        required: true
      - name: query
        in: path
        description: 'URL of an article, DOI, PMCID or PMID in the URL-encoded format. Note that on the Swagger-UI doc page you don''t need to URI-encode the parameter manually, it will be done by the docs engine.

          '
        required: true
        schema:
          type: string
      - name: Accept-Language
        in: header
        description: 'For some articles the result depends on the `Accept-Language` header, so provide it if localized content is required.

          '
        schema:
          type: string
      responses:
        '200':
          description: The citation data in the requested format
          content:
            application/json; charset=utf-8;:
              schema:
                $ref: '#/components/schemas/result'
            application/x-bibtex; charset=utf-8:
              schema:
                $ref: '#/components/schemas/result'
        '404':
          description: Citation data was not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      operationId: getCitation
      x-monitor: false
components:
  schemas:
    problem:
      required:
      - type
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    result:
      required:
      - title
      - url
      - itemType
      type: object
      properties:
        itemType:
          type: string
        title:
          type: string
        url:
          type: string
x-host-basePath: /api/rest_v1
x-default-params: {}
