openapi: 3.2.0
info:
  version: 1.0.0
  title: Wikimedia REST Recommendation API
  description: This API provides cacheable and straightforward access to Wikimedia content and data, in machine-readable formats.
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Services team
    url: http://mediawiki.org/wiki/Wikimedia_REST_API
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
- url: /api/rest_v1
tags:
- name: Recommendation
  description: contribution recommendations
paths:
  /data/recommendation/article/creation/translation/{from_lang}:
    get:
      tags:
      - Recommendation
      summary: Recommend articles for translation
      description: 'Recommends articles to be translated from the source

        to the domain language.


        See more at Recommendation API documentation


        Stability: unstable'
      parameters:
      - name: from_lang
        in: path
        description: The source language code
        required: true
        schema:
          type: string
      - name: count
        in: query
        description: The max number of articles to return
        schema:
          type: integer
          default: 24
      responses:
        '200':
          description: the list of articles recommended for translation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recommendation_result'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      operationId: getDataRecommendationArticleCreationTranslationByFromLang
      x-operation-id-source: derived
  /data/recommendation/article/creation/translation/{from_lang}/{seed_article}:
    get:
      tags:
      - Recommendation
      summary: Recommend articles for translation
      description: 'Recommends articles to be translated from the source

        to the domain language.


        See more at Recommendation API documentation


        Stability: unstable'
      parameters:
      - name: from_lang
        in: path
        description: The source language code
        required: true
        schema:
          type: string
      - name: seed_article
        in: path
        description: The article to use as a search seed
        required: true
        schema:
          type: string
      - name: count
        in: query
        description: The max number of articles to return
        schema:
          type: integer
          default: 24
      responses:
        '200':
          description: the list of articles recommended for translation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recommendation_result'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      operationId: getDataRecommendationArticleCreationTranslationByFromLangBySeedArticle
      x-operation-id-source: derived
  /data/recommendation/article/creation/morelike/{seed_article}:
    get:
      tags:
      - Recommendation
      summary: Recommend missing articles
      description: 'Recommends articles similar to the seed article but are missing

        from the domain language Wikipedia.


        Stability: unstable'
      parameters:
      - name: seed_article
        in: path
        description: The article title used to search similar but missing articles
        required: true
        schema:
          type: string
      responses:
        '200':
          description: the prioritized list of Wikidata IDs recommended for creation as Wikipedia articles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/morelike_result'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      operationId: getDataRecommendationArticleCreationMorelikeBySeedArticle
      x-operation-id-source: derived
components:
  schemas:
    recommendation_result:
      type: object
      properties:
        count:
          type: integer
          description: the number of recommendations returned
        items:
          type: array
          description: the list of articles recommended for translation
          items:
            type: object
            properties:
              wikidata_id:
                type: string
                description: wikidata id for the item
              title:
                type: string
                description: title of the article in the source language
              sitelink_count:
                type: integer
                description: count of sites the wikidata item is linked to
    problem:
      required:
      - type
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    morelike_result:
      type: array
      description: the prioritized list of Wikidata IDs recommended for creation as Wikipedia articles
      items:
        type: object
        properties:
          wikidata_id:
            type: string
            description: Wikidata ID for the item
          score:
            type: number
            description: Score of the recommendation. The higher the score, the more important the recommendation is.
          source_language:
            type: string
            description: Source of the recommendation -- which wiki is recommending the current article.
x-host-basePath: /api/rest_v1
x-default-params: {}
